name: CraftVouchers
version: 1.0
main: pw.ollie.craftvouchers.CraftVouchersPlugin

commands:
  voucher:
    description: Command for all voucher-related functions

permissions:
  craftvouchers.admin:
    description: Admin command access
